add brandon's info for rnn lecture
ucfsigai/data-science pull request #8
Opened 2019-01-05 05:32 UTC by brandons209

2019-01-05 14:50 UTC, jmuchovej requested changes
@brandons209 prepend your name in the `inst` list – @ionlights is essentially an editor, even though you'll likely draw from most of his source material. 😅

2019-01-05 14:50 UTC, ionlights commented on sp19/syllabus.yml
> +  inst: ["ionlights", "brandons209"]
@brandons209 prepend your name, i'm essentially an editor on this, even though i'm anticipating major usage of my source material. 😅

2019-01-06 20:12 UTC, brandons209 reviewed
my name is already there.

2019-01-06 20:36 UTC, brandons209 reviewed
okay fixed

2019-01-07 01:32 UTC, jmuchovej approved these changes

2019-01-07 01:32 UTC, merged